name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '27 5 * * 2'
  push:
    branches: [main]

permissions: read-all

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2
        with:
          persist-credentials: false

      - name: Run the analysis
        uses: ossf/scorecard-action@55891bbd73f2425e97637d96e306fc9d491d0b21 # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload the SARIF artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Publish the results
        uses: github/codeql-action/upload-sarif@88585263c0627ee42c0e1c5143a112c8d6f4aa18 # v4.38.2
        with:
          sarif_file: results.sarif
